encoding: UTF-8

url: "https://pqvst.com"
title: PQVST
description: I build things

markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty

exclude:
  - .git/
  - package.json
  - package-lock.json
  - node_modules

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - rouge

exclude:
  - .git/
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - package.json
  - yarn.lock

defaults:
  - scope:
      path: "assets"
    values:
      image: true
