encoding: UTF-8

url: "https://pqvst.com"
title: PQVST
description: I build things

theme: null

markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - rouge

exclude:
  - .git
  - .gitignore
  - package.json
  - package-lock.json
  - yarn.lock
  - node_modules
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md

defaults:
  - scope:
      path: "assets"
    values:
      image: true
