encoding: UTF-8

title: "pqvst"

description: "pqvst"

theme: jekyll-theme-primer

markdown: kramdown

kramdown:
  auto_ids: true

highlighter: rouge

permalink: pretty

exclude:
  - .git/
  - package.json
  - package-lock.json
  - node_modules

sass:
  sass_dir: ./
  style: compressed

plugins:
  - jekyll-seo-tag
  - rouge

twitter:
  username: pqvst

author:
  name: Philip Bergqvist
  twitter: pqvst

defaults:
  - scope:
      path: "assets"
    values:
      image: true
